# Generated by Django 4.2.2 on 2023-06-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Products'},
        ),
    ]
